### ISSUE TITLE
虚拟机下反应很慢

### ISSUE THREAD

**Issue by wyp7788** [NJU-ProjectN/nvboard#15]
在虚拟机的Ubuntu20.04系统下运行nvboard，界面出来很卡，请问有没有解决办法？？？

**Comment by sashimi-yzh** [comment]
我这边复现不了, 建议做一下profiling, 提供一些有用的性能数据

**Comment by zlh20040308** [comment]
我用的是WSL2，也出现了延迟问题

**Comment by zlh20040308** [comment]
> 在虚拟机的Ubuntu20.04系统下运行nvboard，界面出来很卡，请问有没有解决办法？？？

你可以看一下https://github.com/NJU-ProjectN/nvboard/issues/14

**Comment by Gs-ygc** [comment]
目测高刷高分屏SDL有这bug，没细看。英伟达4060laptop ubuntu2204 535驱动，只要使用SDL开发的应用就会出现SDL事件响应延迟、并且我的会使得我的KDE5.9的应用特效失效、桌面卡死等。

**Comment by sashimi-yzh** [comment]
由于长时间无反馈, 本issue将关闭.
