### ISSUE TITLE
尝试控制时钟频率时,NVboard出现黑屏之后无法控制

### ISSUE THREAD

**Issue by xiaodou1117** [NJU-ProjectN/nvboard#28]
当我在single_cycle中写入以下代码时,
void single_cycle(){
    top.clk = 0;
    top.eval();
    sleep(1); 
    
    top.clk = 1;
    top.eval();
    sleep(1);
}
尝试让时钟更新慢一些,但是nvboard先黑屏然后无法控制

![nvboard](https://github.com/NJU-ProjectN/nvboard/assets/56909833/2ef9c823-d48a-4791-a3be-d982b54d6e28)

**Comment by sashimi-yzh** [comment]
按照你的改动, 应该需要等待`reset的周期数*2`这么多秒, nvboard的画面才会出现.

**Comment by sashimi-yzh** [comment]
由于长时间无反馈, 本issue将关闭.
