### ISSUE TITLE
运行example报错

### ISSUE THREAD

**Issue by dowdyboy** [NJU-ProjectN/nvboard#31]
![image](https://github.com/NJU-ProjectN/nvboard/assets/39474100/d3033ead-bebe-46bf-be9b-a46c35dae0c6)

猜测是否是依赖版本不对？
系统版本是Ubuntu2004

**Comment by sashimi-yzh** [comment]
用Ubuntu 22.04是可以的

**Comment by zyk007** [comment]
我使用的系统也是Ubuntu20.04，直接使用apt下载的依赖是不可以的。
我的解决方法是到官方下载去下载新版的sdl2、sdl2_image、sdl2_ttf。然后使用make install安装到系统，以下是我的下载链接：
sdl2: https://wiki.libsdl.org/SDL2/Installation (按照Linux/Unix那一个部分的指示安装)
sdl2_image: 直接 apt install libsdl2-image-dev
sdl2_ttf: https://github.com/libsdl-org/SDL_ttf/releases/download/release-2.22.0/SDL2_ttf-2.22.0.tar.gz

sdl2_ttf文件下载后直接用tar -xvf SDL2_ttf-2.22.0.tar.gz解压，然后依次执行：
./autogen.sh
./configure
make install

我成功运行了，目前看起来没有问题

**Comment by dowdyboy** [comment]
> 我使用的系统也是Ubuntu20.04，直接使用apt下载的依赖是不可以的。 我的解决方法是到官方下载去下载新版的sdl2、sdl2_image、sdl2_ttf。然后使用make install安装到系统，以下是我的下载链接： sdl2: https://wiki.libsdl.org/SDL2/Installation (按照Linux/Unix那一个部分的指示安装) sdl2_image: 直接 apt install libsdl2-image-dev sdl2_ttf: https://github.com/libsdl-org/SDL_ttf/releases/download/release-2.22.0/SDL2_ttf-2.22.0.tar.gz
> 
> sdl2_ttf文件下载后直接用tar -xvf SDL2_ttf-2.22.0.tar.gz解压，然后依次执行： ./autogen.sh ./configure make install
> 
> 我成功运行了，目前看起来没有问题

十分感谢，我尝试一下

**Comment by ssl234231** [comment]
make run之后就出现 fatal error: sdl_image.h: 没有那个文件或目录，但在根目录下写了一个测试文件运行gcc test.c -lSDL2 -lSDL2_image编译是通过的，也有正常的输出，我的sdl文件和sdl_ttf都在根目录下存放

**Comment by ssl234231** [comment]
make run之后就出现/home/ssl/ysyx-workbench/nvboard/include/nvboard.h:11:10: fatal error: SDL_image.h: 没有那个文件或目录
 ，但在根目录下写了一个测试文件运行gcc test.c -lSDL2 -lSDL2_image编译是通过的，也有正常的输出，我的sdl文件和sdl_ttf都在根目录下存放

**Comment by HUSTJunshuang** [comment]
> make run之后就出现/home/ssl/ysyx-workbench/nvboard/include/nvboard.h:11:10: fatal error: SDL_image.h: 没有那个文件或目录 ，但在根目录下写了一个测试文件运行gcc test.c -lSDL2 -lSDL2_image编译是通过的，也有正常的输出，我的sdl文件和sdl_ttf都在根目录下存放

xd我解决了，是这样子的，那两个make install的默认路径都是`/usr/local/include`，但是apt安装的image库在`/usr/include`，local是多余的，你`make uninstall`一下然后`./configure --prefix /usr`配置的时候改一下前缀再编译安装就在`/usr/include`下了。

**Comment by Dragonzhoulong** [comment]
还是在/etc/apt/source.list末尾加一行
deb http://archive.ubuntu.com/ubuntu jammy main universe
然后更新软件列表
sudo apt-get update
再安装特定软件
sudo apt-get install -t jammy libsdl2-dev
sudo apt-get install -t jammy libsdl2-image-dev
sudo apt-get install -t jammy libsdl2-ttf-dev	
最后再注释掉新增的软件源就好了

**Comment by tiantongzhang6** [comment]
系统kylin，2个库函数都要求[SDL_ttf 2.0.18以上](https://wiki.libsdl.org/SDL2_ttf/TTF_RenderText_Shaded_Wrapped)(https://wiki.libsdl.org/SDL2_ttf/TTF_SetFontSize)，且ubuntu20默认是2.0.15版本.
![2024-08-14_12-09-03](https://github.com/user-attachments/assets/6928224f-865b-4d3f-a4ef-b463ece62045)

**Comment by sashimi-yzh** [comment]
看起来问题已解决, 本issue将关闭.
