### ISSUE TITLE
如何理解nvboard无系统clk

### ISSUE THREAD

**Issue by ccnuktd** [NJU-ProjectN/nvboard#33]
我在查看N4文件的时候，发现nvboard并没有系统级的clk，只有vga和ps2的clk。但是我在看example代码的时候，发现引脚绑定并不需要绑定top的clk。想问问是否有默认top中的clk不需要绑定的设计，这个clk与vga和ps2的clk有什么样的区别和联系？

**Comment by sashimi-yzh** [comment]
top的clk是由verilator的仿真代码驱动的, 如果你感兴趣, 可以先了解一下如何用verilator进行仿真.

**Comment by ccnuktd** [comment]
> top的clk是由verilator的仿真代码驱动的, 如果你感兴趣, 可以先了解一下如何用verilator进行仿真.

谢谢你，我去了解一下
