### ISSUE TITLE
example/csrc/main.cpp 中的 TOP_NAME

### ISSUE THREAD

**Issue by Luyoung0001** [NJU-ProjectN/nvboard#37]
```c
#include <nvboard.h>
#include "../build/obj_dir/Vtop.h"

static Vtop dut;

void nvboard_bind_all_pins(Vtop* top);
```
以下代码会标红警告：
```c
#include <Vtop.h>

static TOP_NAME dut;

void nvboard_bind_all_pins(TOP_NAME* top);
```
我认为这种写法不规范，而且容易造成歧义，比如如果在 example 中进行 make all 编译，Vtop.h 的路径并不对，而且TOP_NAME是一个不存在的类型。

**Comment by sashimi-yzh** [comment]
我这边在example中进行`make all`, 编译是成功的.

**Comment by Luyoung0001** [comment]
> 我这边在example中进行`make all`, 编译是成功的.

确实是可以成功的，因为在 Makefile 中定义了一个宏`CXXFLAGS += $(INCFLAGS) -DTOP_NAME="\"V$(TOPNAME)\""`，所以TOP_NAME 是可以编译通过的，但是这种在编译时添加宏的做法很不规范，毕竟在写代码的时候VOP_NAME 是不存在的类型

**Comment by sashimi-yzh** [comment]
> 但是这种在编译时添加宏的做法很不规范

请问是否可以提供“说明这种做法很不规范”的编程规范链接？

**Comment by Luyoung0001** [comment]
> > 但是这种在编译时添加宏的做法很不规范
> 
> 请问是否可以提供“说明这种做法很不规范”的编程规范链接? 我看在类似[这样](https://users.ece.cmu.edu/~eno/coding/CCodingStandard.html)的编程规范里面并没有提到相关说法.

那只是我的个人看法，客观上那样写是没有任何问题的。
